create_district_chart:
  description: >
    利用QuickChart工具，根据各街道事件数量统计数据创建一个条形图。
    图表应清晰展示各街道事件数量的对比，并按降序排列。
    
    确保图表具有以下特征：
    - 使用鲜明但专业的颜色
    - 包含清晰的标题和轴标签
    - 条形标签显示具体数值
    - 适当的尺寸，便于嵌入报告
    
    输入数据格式为：{district_data}
  expected_output: >
    一个展示各街道事件数量统计的条形图URL和相应的描述文本。
  agent: chart_designer

create_ev_violations_chart:
  description: >
    利用QuickChart工具，根据存在电动车违规问题的社区列表创建一个饼图。
    图表应清晰展示不同社区电动车违规问题的分布情况。
    
    确保图表具有以下特征：
    - 使用鲜明但专业的颜色
    - 包含清晰的标题和图例
    - 显示各部分的百分比
    - 适当的尺寸，便于嵌入报告
    
    输入数据格式为：{communities}
  expected_output: >
    一个展示电动车违规问题社区分布的饼图URL和相应的描述文本。
  agent: chart_designer

create_garbage_stats_chart:
  description: >
    利用QuickChart工具，根据各社区暴露垃圾问题数量统计创建一个条形图。
    图表应清晰展示各社区垃圾问题数量的对比，并按数量降序排列。
    
    确保图表具有以下特征：
    - 使用鲜明但专业的颜色
    - 包含清晰的标题和轴标签
    - 条形标签显示具体数值
    - 适当的尺寸，便于嵌入报告
    
    输入数据格式为：{community_data}
  expected_output: >
    一个展示各社区暴露垃圾问题数量的条形图URL和相应的描述文本。
  agent: chart_designer

create_garbage_sources_chart:
  description: >
    利用QuickChart工具，根据暴露垃圾事件主要来源统计创建一个饼图。
    图表应清晰展示不同来源的占比情况。
    
    确保图表具有以下特征：
    - 使用鲜明但专业的颜色
    - 包含清晰的标题和图例
    - 显示各部分的百分比
    - 适当的尺寸，便于嵌入报告
    
    输入数据格式为：{source_data}
  expected_output: >
    一个展示暴露垃圾事件主要来源的饼图URL和相应的描述文本。
  agent: chart_designer