write_report_section_1:
  description: >
    根据各街道事件数量统计分析和对应图表，撰写报告第一部分。
    内容应包括：
    - 统计结果的概述
    - 事件分布的主要趋势
    - 重点关注的高事件街道
    - 可能的原因分析
    - 建议的行动方案
    
    确保内容清晰、简洁，与图表内容相互呼应，便于决策者理解。
    
    输入数据：
    - 统计数据：{district_data}
    - 图表：{district_data_chart_data}
    - 数据解读：{interpretation}
  expected_output: >
    一个包含标题、正文内容和图表引用的报告章节。
  agent: report_writer

write_report_section_2:
  description: >
    根据电动车违规问题社区分析和对应图表，撰写报告第二部分。
    内容应包括：
    - 电动车违规问题的概述
    - 重点问题社区的分析
    - 可能的原因和影响
    - 针对性的解决建议
    
    确保内容清晰、简洁，与图表内容相互呼应，便于决策者理解。
    
    输入数据：
    - 统计数据：{communities}
    - 图表：{communities_chart_data}
    - 数据解读：{interpretation}
  expected_output: >
    一个包含标题、正文内容和图表引用的报告章节。
  agent: report_writer

write_report_section_3:
  description: >
    根据各社区暴露垃圾问题数量统计和对应图表，撰写报告第三部分。
    内容应包括：
    - 垃圾问题的总体情况
    - 问题严重社区的具体分析
    - 垃圾问题的可能原因
    - 改善环境卫生的建议措施
    
    确保内容清晰、简洁，与图表内容相互呼应，便于决策者理解。
    
    输入数据：
    - 统计数据：{community_data}
    - 图表：{community_data_chart_data}
    - 数据解读：{interpretation}
  expected_output: >
    一个包含标题、正文内容和图表引用的报告章节。
  agent: report_writer

write_report_section_4:
  description: >
    根据暴露垃圾事件主要来源统计和对应图表，撰写报告第四部分。
    内容应包括：
    - 垃圾事件来源的总体分布
    - 主要来源类型的分析
    - 不同来源的影响比较
    - 针对主要来源的治理建议
    
    确保内容清晰、简洁，与图表内容相互呼应，便于决策者理解。
    
    输入数据：
    - 统计数据：{source_data}
    - 图表：{source_data_chart_data}
    - 数据解读：{interpretation}
  expected_output: >
    一个包含标题、正文内容和图表引用的报告章节。
  agent: report_writer