compile_final_report:
  description: >
    整合四个报告章节，编写报告的引言和结论部分，完成最终的坪山热线报告。
    报告应包含：
    - 引言：介绍报告背景、目的和数据来源
    - 四个核心章节：按顺序整合已完成的章节内容
    - 结论：总结主要发现和建议，提出下一步行动计划
    
    确保报告格式统一，结构清晰，便于阅读和理解。
    
    输入数据：
    - 报告章节1：{section_1}
    - 报告章节2：{section_2}
    - 报告章节3：{section_3}
    - 报告章节4：{section_4}
  expected_output: >
    一份完整的坪山热线报告，包含引言、四个核心章节和结论。
  agent: report_writer