district_event_stats:
  description: >
    使用SQL查询工具generate_execute_sql查询：按街道名称统计事件数量并按数量降序排序。
    
  expected_output: >
    一个包含各街道事件数量统计（按数量降序排列）的结果集，格式为字典结构。
  agent: sql_analyst

electric_vehicle_violations:
  description: >
    使用SQL查询工具generate_execute_sql查询：找出存在电动车违规问题的社区。

  expected_output: >
    一个包含所有存在电动车违规问题的社区名称列表。
  agent: sql_analyst

garbage_exposure_stats:
  description: >
    使用SQL查询工具generate_execute_sql查询：统计各社区暴露垃圾问题的数量。
    
  expected_output: >
    一个包含各社区暴露垃圾问题数量统计的结果集，格式为字典结构。
  agent: sql_analyst

garbage_sources:
  description: >
    使用SQL查询工具generate_execute_sql查询：暴露垃圾事件的主要来源。
    
  expected_output: >
    一个包含暴露垃圾事件各来源数量统计的结果集，格式为字典结构。
  agent: sql_analyst

interpret_results:
  description: >
    解释所有SQL查询结果，提取关键信息并提供有价值的见解。
    请分析以下四个方面的数据：
    1. 各街道事件数量统计（按数量降序）
    2. 存在电动车违规问题的社区列表
    3. 各社区暴露垃圾问题数量统计
    4. 暴露垃圾事件的主要来源统计
    
    针对每个结果，提供以下内容：
    - 数据的主要趋势和模式
    - 异常值或特殊情况的说明
    - 可能的原因分析
    - 潜在的行动建议
    
    确保分析内容清晰、简洁，便于决策者理解。
  expected_output: >
    一份包含四个部分的数据解读报告，每部分针对一个查询结果提供详细分析和建议。
  agent: data_interpreter