research_topic:
  description: >
    研究所提供的主题 {topic}，收集对制定图书大纲最有用的重要信息。
    请确保专注于高质量、可靠的资料来源。

    以下是作者对本书目标的补充说明：\n\n {goal}
  expected_output: >
     一组关于 {topic} 的关键点和重要信息，将用于制定图书大纲。
  agent: researcher

generate_outline:
  description: >
    根据研究结果，创建一本书的章节大纲，按顺序排列。
    确保每一章都有标题和简要描述，突出将要涵盖的主题和子主题。
    请注意，每一章的长度不得超过 3,000 字。
    还要确保不要在大纲中重复章节或主题。

    以下是作者对本书目标的补充说明：\n\n {goal}

  expected_output: >
    包含章节标题和各章内容描述的图书大纲。
  agent: outliner
