research_chapter:
  description: >
    研究所提供的章节主题、标题和大纲，收集有助于撰写该章节的补充内容。
    请确保专注于可靠且高质量的信息来源。

    以下是作者对整本书和本章节的目标补充说明：\n\n {goal}
    以下是该章节的大纲描述：\n\n {chapter_description}

    在进行研究时，请考虑以下关键点：
    - 你需要收集足够的信息，以支持撰写一篇约 3,000 字的章节内容
    - 该章节的内容需要与本书其余章节良好衔接。

    以下是整本书的大纲：\n\n
    {book_outline}
  expected_output: >
    一组可用于撰写该章节的补充见解与信息。
  agent: researcher

write_chapter:
  description: >
    根据章节标题、写作目标和大纲描述，撰写结构合理的章节内容。
    每一章应采用 Markdown 格式编写，字数控制在约 3,000 字。

    本书主题为：{topic}
    本章节标题为：{chapter_title}
    以下是该章节的大纲描述：\n\n {chapter_description}

    重要说明：
    - 你所撰写的章节内容应当与整本书的其他章节协调一致。

    以下是整本书的大纲：\n\n
    {book_outline}
  expected_output: >
    一篇以 Markdown 格式撰写、围绕章节标题与大纲内容展开的约 3,000 字的章节内容。
  agent: writer
