query_hotline_data:
  description: >
    使用SQL查询工具获取坪山热线系统的数据，
    并对获取的数据进行初步分析和统计。需要执行的关键查询包括：
    
    1. 按街道名称统计事件数量，并按数量降序排序
    2. 找出哪些社区存在电动车违规问题
    3. 统计各社区暴露垃圾问题的数量
    4. 暴露垃圾事件的主要来源是什么
    
    请确保每个查询都有明确的目的，并关注数据的质量和完整性。注意不要限制查询时间为固定年月，查询全部数据。
  expected_output: >
    包含各类SQL查询结果的结构化数据集，以便后续进行可视化和报告生成。
  agent: data_analyst

create_visualizations:
  description: >
    基于SQL查询结果，使用QuickChart服务创建清晰、直观的图表，以便在月度报告中展示数据趋势和发现。
    
    需要生成的关键图表包括：
    
    1. 热点街道TOP10柱状图：展示事件数量最多的10个街道
    2. 电动车违规问题社区分布图：展示存在电动车违规问题的社区分布
    3. 暴露垃圾问题社区分布柱状图：展示各社区暴露垃圾问题的数量
    4. 暴露垃圾事件来源饼图：展示暴露垃圾事件的主要来源占比
    
    请确保每个图表都有清晰的标题、坐标轴标签和图例说明，并选择合适的颜色方案以提高可读性。
  expected_output: >
    一组用于月度报告的高质量数据可视化图表，包括图表URL链接和图表类型说明。
  agent: visualization_expert