query_hotline_data:
  description: >
    使用SQL查询工具获取坪山热线系统在 {start_date} 到 {end_date} 期间的数据，
    并对获取的数据进行初步分析和统计。需要执行的关键查询包括：
    
    1. 总体事件统计：在指定时间段内的总事件数、日均事件数、处理率等
    2. 分类统计：按一级分类、二级分类、三级分类、四级分类和末级分类进行统计
    3. 地域分布：按街道、社区、网格划分统计事件数量
    4. 时间分布：按日期、时段统计事件数量，分析高峰期
    5. 来源渠道：按事件渠道和来源统计
    6. 处置部门：按实际处置部门和经办部门统计
    7. 事件性质统计
    8. 标签分析：按地理标签、话题标签、专项标签进行统计
    
    请确保每个查询都有明确的目的，并关注数据的质量和完整性。
  expected_output: >
    包含各类SQL查询结果的结构化数据集，以便后续进行可视化和报告生成。
  agent: data_analyst

create_visualizations:
  description: >
    基于SQL查询结果，使用QuickChart服务创建清晰、直观的图表，以便在月度报告中展示数据趋势和发现。
    
    需要生成的关键图表包括：
    
    1. 事件数量趋势图：显示每日事件数量变化趋势
    2. 一级分类占比饼图：展示不同一级分类的事件数量占比
    3. 热点街道TOP10柱状图：展示事件数量最多的10个街道
    4. 事件来源渠道饼图：展示不同渠道的事件数量占比
    5. 热点分类TOP10柱状图：展示事件数量最多的10个末级分类
    6. 处置部门工作量柱状图：展示各部门处理的事件数量
    7. 每日处理率折线图：展示每日的事件处理率变化
    8. 热门话题标签词云图：展示频次最高的话题标签
    
    请确保每个图表都有清晰的标题、坐标轴标签和图例说明，并选择合适的颜色方案以提高可读性。
  expected_output: >
    一组用于月度报告的高质量数据可视化图表，包括图表URL链接和图表类型说明。
  agent: visualization_expert