interpret_data:
  description: >
    基于 {month} 月 {year} 年的数据分析结果和生成的图表，提供专业的数据解读，
    识别关键趋势、异常和模式，提取有价值的洞察。
    
    需要解读的关键方面包括：
    
    1. 总体情况：总体事件数量、处理率和响应速度的趋势和变化
    2. 分类分布：热门分类和异常分类的识别及其可能的原因
    3. 地域分布：热点区域和特殊区域的识别及其可能的原因
    4. 时间分布：事件高峰期和低谷期的识别及其可能的原因
    5. 渠道效率：不同渠道的效率和质量比较
    6. 部门表现：不同处置部门的工作量和效率比较
    7. 特殊话题：基于标签分析识别的热门话题和特殊事件
    
    请确保解读既有总体概述，也有针对具体问题的深入分析，并结合图表数据提供有力的支持。
  expected_output: >
    一组结构化的数据解读结果，包括对各个关键方面的专业解读和洞察。
  agent: data_interpreter

write_report:
  description: >
    基于数据分析结果、数据可视化和数据解读，撰写 {month} 月 {year} 年坪山热线系统月度分析报告。
    
    报告应包括以下部分：
    
    1. 执行摘要：简要概述报告的主要发现和建议
    2. 总体情况：总体事件数量、处理率和响应速度的分析
    3. 分类分析：按不同分类维度的事件分布分析
    4. 地域分析：按地域维度的事件分布分析
    5. 时间分析：按时间维度的事件分布分析
    6. 来源分析：按事件来源和渠道的分析
    7. 部门工作量分析：各处置部门的工作量和效率分析
    8. 热点话题分析：基于标签分析的热点话题和特殊事件
    9. 建议与展望：基于分析结果提出的改进建议和下月展望
    
    请确保报告语言专业清晰，结构有序，内容全面，并适当引用数据和图表来支持分析结果。
  expected_output: >
    一份结构完整、内容全面的月度分析报告，包括摘要、各个分析部分和建议。
  agent: report_writer