analyze_market:
  description: >
    研究停车场市场的动态定价模型和最佳实践。重点关注以下几个方面：
    1. 停车场动态调价的常见模型和方法
    2. 不同类型场所（博物馆、商场、机场等）的调价策略差异
    3. 停车场定价与充电服务价格的协同优化
    4. 竞争对手的定价策略和市场反应

    你需要针对以下具体问题进行研究：{question}
  expected_output: >
    一份关于停车场动态定价市场的详细分析报告，包括主流模型、最佳实践和竞争情况。
  agent: market_researcher

analyze_user_behavior:
  description: >
    分析停车场用户的行为模式和价格敏感度。重点关注以下几个方面：
    1. 不同时段用户停车需求变化规律
    2. 不同用户群体（临时用户、高频用户等）的价格敏感度
    3. 用户对不同区域车位的偏好和支付意愿
    4. 价格变动对用户行为的影响预测模型

    你需要针对以下具体问题进行研究：{question}
  expected_output: >
    一份关于停车场用户行为和价格敏感度的详细分析报告，包括用户分群、行为模式和价格弹性预测。
  agent: user_analyst